// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:81ec9f68-d052-43ff-ac2d-c08d9bfb2b62",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_LFU735AnE",
    "aws_user_pools_web_client_id": "7bs13tdjhvc0c4966urcualo1o",
    "oauth": {},
    "aws_content_delivery_bucket": "askanager-20200113205402-hostingbucket-env",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://d2xajl4nwchz3k.cloudfront.net"
};


export default awsmobile;
